version: '3'

services:
  api:
    container_name: dpstore-api
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    env_file: .env
    ports:
      - 3229:9229
      - 3001:3001
    volumes:
      - ./src:/home/app/src:cached
      - ./package.json:/home/app/package.json:cached
      - ./schema.gql:/home/app/schema.gql:cached
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo:/data/db:cached